// <auto-generated />
interface Window {
  electron: ElectronAPI
}

interface ElectronAPI {
  appQuit: () => void
  jobGetUpdateAppRunningStatusJobStatus: () => Promise<UpdateAppRunningStatusJobStatus>
  settingGet: () => Promise<AppSettings>
  settingUpdate: (param: AppSettingsPatch) => Promise<boolean>
  shellOpenExternal: (param: string) => void
  shellOpenPath: (param: string) => void
  steamChangeLoginUser: (param: ChangeSteamUserRequest) => Promise<boolean>
  steamDiscardUseAppRecording: () => Promise<boolean>
  steamEndUseAppRecording: () => Promise<boolean>
  steamFriendsGetAll: () => Promise<SteamFriendData[]>
  steamFriendsGetCached: () => Promise<SteamFriendData[]>
  steamFriendsGetForUser: (param: AccountNameRequest) => Promise<SteamFriendData | null>
  steamFriendsRecordsClear: (param?: FriendStatusRecordsClearRequest) => Promise<number>
  steamFriendsRecordsGet: (param?: FriendStatusRecordsQueryRequest) => Promise<FriendStatusRecord[]>
  steamFriendsRequestFriendInfo: (param: SteamFriendInfoRequest) => void
  steamFriendsTrackGet: (param: AccountNameRequest) => Promise<string[]>
  steamFriendsTrackGetAll: () => Promise<Record<string, string[]>>
  steamFriendsTrackStart: (param: SteamFriendsTrackingRequest) => Promise<boolean>
  steamFriendsTrackStop: (param: SteamFriendsTrackingRequest) => Promise<boolean>
  steamFriendsUpdateOnListener: (callback: (data: SteamFriendsUpdateEvent) => void) => void
  steamFriendsUpdateRemoveListener: () => void
  steamGetAppsInfo: (param?: SteamAppsQueryRequest) => Promise<SteamApp[]>
  steamGetLibraryFolders: () => Promise<string[]>
  steamGetLoginUser: () => Promise<SteamUser[]>
  steamGetRunningApps: () => Promise<RunningApps>
  steamGetStatus: () => Promise<GlobalStatus | null>
  steamGetUsersInRecord: () => Promise<SteamUser[]>
  steamGetValidUseAppRecord: (param?: UseAppRecordsQueryRequest) => Promise<UseAppRecords>
  steamLibraryGetForAllUsers: () => Promise<Record<string, SteamOwnedGame[]>>
  steamLibraryGetForUser: (param: AccountNameRequest) => Promise<SteamOwnedGame[]>
  steamLibrarySyncForAllUsers: () => Promise<Record<string, boolean>>
  steamLibrarySyncForUser: (param: AccountNameRequest) => Promise<boolean>
  steamLoginCancel: () => void
  steamLoginConfirmDevice: () => void
  steamLoginCredentialsStart: (param: SteamLoginCredentialsRequest) => Promise<SteamLoginResult>
  steamLoginEventOnListener: (callback: (data: SteamLoginEvent) => void) => void
  steamLoginEventRemoveListener: () => void
  steamLoginGuardCodeSubmit: (param: SteamLoginGuardCodeRequest) => Promise<boolean>
  steamLoginLoggedInUsersGet: () => Promise<string[]>
  steamLoginQrStart: (param: SteamLoginQrRequest) => Promise<SteamLoginResult>
  steamLoginSavedTokenDelete: (param: SteamLoginTokenDeleteRequest) => Promise<boolean>
  steamLoginSavedTokensGet: () => Promise<SteamLoginToken[]>
  steamLoginSwitchToUseCode: () => void
  steamLoginTokenStart: (param: SteamLoginTokenRequest) => Promise<SteamLoginResult>
  steamLoginUserLogout: (param: AccountNameRequest) => Promise<boolean>
  steamLoginUserSetPersonaState: (param: SteamPersonaStateRequest) => Promise<boolean>
  steamRefreshAppsInfo: (param?: SteamAppsQueryRequest) => Promise<SteamApp[]>
  steamRefreshLoginUser: () => Promise<SteamUser[]>
  steamRefreshStatus: () => Promise<GlobalStatus | null>
  steamUserUpdatedOnListener: (callback: () => void) => void
  steamUserUpdatedRemoveListener: () => void
  updaterCheck: () => void
  updaterDownload: () => void
  updaterEventOnListener: (callback: (data: UpdaterEvent) => void) => void
  updaterEventRemoveListener: () => void
  updaterGetStatus: () => Promise<UpdaterStatus>
  updaterQuitAndInstall: () => void
  windowClose: () => void
  windowIsMaximized: () => Promise<boolean>
  windowMaximize: () => Promise<boolean>
  windowMinimize: () => void
  windowMinimizeToTray: () => void
}

interface AccountNameRequest {
  accountName: string
}

interface AppSettings {
  autoStart: boolean
  autoUpdate: boolean
  closeAction: 'exit' | 'minimize' | 'ask'
  colorScheme: 'light' | 'dark' | 'system'
  experimentalFeatures: boolean
  homePage: '/status' | '/user' | '/app' | '/useRecord'
  language: 'zh-CN' | 'en-US'
  radius: number
  silentStart: boolean
  themeColor: string
  updateAppRunningStatusJob: UpdateAppRunningStatusJobSettings
  zoomFactor: number
}

interface AppSettingsPatch {
  autoStart?: boolean | null
  autoUpdate?: boolean | null
  closeAction?: 'exit' | 'minimize' | 'ask' | null
  colorScheme?: 'light' | 'dark' | 'system' | null
  experimentalFeatures?: boolean | null
  homePage?: '/status' | '/user' | '/app' | '/useRecord' | null
  language?: 'zh-CN' | 'en-US' | null
  radius?: number | null
  silentStart?: boolean | null
  themeColor?: string | null
  updateAppRunningStatusJob?: UpdateAppRunningStatusJobSettingsPatch | null
  zoomFactor?: number | null
}

interface ChangeSteamUserRequest {
  accountId: number
  accountName: string
  allowAutoLogin?: boolean | null
  animatedAvatar?: string | null
  avatarFrame?: string | null
  avatarFull?: string | null
  avatarMedium?: string | null
  avatarSmall?: string | null
  id: number
  level?: number | null
  levelClass?: string | null
  mostRecent?: boolean | null
  offlineMode?: boolean | null
  personaName?: string | null
  personaState?: number | null
  rememberPassword?: boolean | null
  skipOfflineModeWarning?: boolean | null
  steamId: string
  timestamp?: number | null
  wantsOfflineMode?: boolean | null
}

interface FriendStatusRecord {
  accountName: string
  changeType: string
  currentValue?: string | null
  friendPersonaName: string
  friendSteamId: string
  id: number
  previousValue?: string | null
  timestamp: number
}

interface FriendStatusRecordsClearRequest {
  accountName?: string | null
  friendSteamId?: string | null
}

interface FriendStatusRecordsQueryRequest {
  accountName?: string | null
  changeType?: string | null
  endTime?: number | null
  friendSteamId?: string | null
  limit?: number | null
  startTime?: number | null
}

interface GlobalStatus {
  activeUserSteamId?: string | null
  id: number
  refreshTime: number
  runningAppId?: number | null
  steamAppRefreshTime?: number | null
  steamClientDll64Path?: string | null
  steamClientDllPath?: string | null
  steamExePath?: string | null
  steamPath?: string | null
  steamPid?: number | null
  steamUserRefreshTime?: number | null
}

interface RunningApps {
  apps: SteamApp[]
  lastUpdateTime: number
}

interface SteamApp {
  appId: number
  appOnDisk?: number | null
  appOnDiskReal?: number | null
  developer?: string | null
  id: number
  installDir?: string | null
  installDirPath?: string | null
  installed: boolean
  isFreeApp?: boolean | null
  isRunning: boolean
  name?: string | null
  nameLocalized: string
  publisher?: string | null
  steamReleaseDate?: number | null
  type?: string | null
}

interface SteamAppsQueryRequest {
  filterInstalled?: boolean | null
  sortField?: 'appId' | 'name' | 'installDir' | 'appOnDisk' | null
  sortOrder?: 'asc' | 'desc' | null
}

interface SteamFriendData {
  accountName: string
  currentUser: SteamFriendInfo
  friends: SteamFriendInfo[]
  lastUpdateTime: number
}

interface SteamFriendInfo {
  avatarHash: string
  gameId: string
  gameName: string
  lastLogOff: number
  lastLogOn: number
  level?: number | null
  personaName: string
  personaState: number
  personaStateFlags: number
  relationship: number
  richPresence: string
  steamId: string
}

interface SteamFriendInfoRequest {
  accountName: string
  friendSteamId: string
}

interface SteamFriendsTrackingRequest {
  accountName: string
  friendSteamIds: string[]
}

interface SteamFriendsUpdateEvent {
  accountName: string
  data: SteamFriendData
}

interface SteamLoginCredentialsRequest {
  password: string
  rememberMe: boolean
  username: string
}

interface SteamLoginEvent {
  data?: SteamLoginEventData | null
  type: 'connecting' | 'authenticating' | 'guardCodeNeeded' | 'deviceConfirmationNeeded' | 'qrCode' | 'success' | 'error' | 'cancelled' | 'userDisconnected' | 'userReconnected' | 'reconnectFailed'
}

interface SteamLoginEventData {
  accountName?: string | null
  email?: string | null
  errorCode?: string | null
  guardType?: 'device' | 'email' | null
  message?: string | null
  previousCodeWasIncorrect?: boolean | null
  qrImageBase64?: string | null
}

interface SteamLoginGuardCodeRequest {
  code: string
}

interface SteamLoginQrRequest {
  rememberMe: boolean
}

interface SteamLoginResult {
  accountName?: string | null
  error?: string | null
  errorCode?: string | null
  success: boolean
}

interface SteamLoginToken {
  accountName: string
  createdAt: number
  expiresAt?: number | null
  id: number
}

interface SteamLoginTokenDeleteRequest {
  id: number
}

interface SteamLoginTokenRequest {
  tokenId: number
}

interface SteamOwnedGame {
  achievementPercentage: number
  achievementTotal: number
  achievementUnlocked: number
  appId: number
  contentDescriptorIds: number[]
  hasCommunityVisibleStats: boolean
  imgIconUrl: string
  isFamilyShared: boolean
  isInWishlist: boolean
  isOwned: boolean
  name: string
  nameLocalized: string
  ownerNames: string[]
  ownerSteamIds: string[]
  playtime2Weeks: number
  playtimeForever: number
  rtimeLastPlayed: number
}

interface SteamPersonaStateRequest {
  accountName: string
  personaState: number
}

interface SteamUser {
  accountId: number
  accountName: string
  allowAutoLogin?: boolean | null
  animatedAvatar?: string | null
  avatarFrame?: string | null
  avatarFull?: string | null
  avatarMedium?: string | null
  avatarSmall?: string | null
  id: number
  level?: number | null
  levelClass?: string | null
  mostRecent?: boolean | null
  personaName?: string | null
  rememberPassword?: boolean | null
  skipOfflineModeWarning?: boolean | null
  steamId: string
  timestamp?: number | null
  wantsOfflineMode?: boolean | null
}

interface UpdateAppRunningStatusJobSettings {
  enabled: boolean
  intervalSeconds: number
}

interface UpdateAppRunningStatusJobSettingsPatch {
  enabled?: boolean | null
  intervalSeconds?: number | null
}

interface UpdateAppRunningStatusJobStatus {
  intervalTime: number
  isRunning: boolean
  lastUpdateTime: number
}

interface UpdaterEvent {
  data?: UpdaterEventData | string | null
  updaterEvent: 'checking-for-update' | 'update-available' | 'update-not-available' | 'download-progress' | 'update-downloaded' | 'error'
}

interface UpdaterEventData {
  bytesPerSecond?: number | null
  files?: UpdaterFile[] | null
  message?: string | null
  percent?: number | null
  progress?: string | null
  releaseDate?: string | null
  releaseName?: string | null
  releaseNotes?: UpdaterReleaseNote[] | null
  stagingPercentage?: number | null
  total?: number | null
  transferred?: number | null
  version?: string | null
}

interface UpdaterFile {
  blockMapSize: number
  isAdminRightsRequired: boolean
  sha512: string
  size: number
  url: string
}

interface UpdaterReleaseNote {
  note: string
  version: string
}

interface UpdaterStatus {
  autoUpdateEnabled: boolean
  checkUpdateInterval: number
  currentVersion: string
  isChecking: boolean
  isDownloading: boolean
}

interface UseAppRecord {
  appId: number
  appName?: string | null
  appNameLocalized?: string | null
  duration: number
  endTime: number
  startTime: number
  steamId: string
  userPersonaName?: string | null
}

interface UseAppRecords {
  lastUpdateTime: number
  records: UseAppRecord[]
}

interface UseAppRecordsQueryRequest {
  endDate?: number | null
  startDate?: number | null
  steamIds?: string[] | null
}
