export const lightTheme = {
  'color-scheme': 'light',
  // shadcn
  '--background': 'hsl(0 0% 100%)',
  '--foreground': 'hsl(240 10% 3.9%)',
  '--card': 'hsl(0 0% 100%)',
  '--card-foreground': 'hsl(240 10% 3.9%)',
  '--popover': 'hsl(0 0% 100%)',
  '--popover-foreground': 'hsl(240 10% 3.9%)',
  '--primary': 'hsl(240 5.9% 10%)',
  '--primary-foreground': 'hsl(0 0% 98%)',
  '--secondary': 'hsl(240 4.8% 95.9%)',
  '--secondary-foreground': 'hsl(240 5.9% 10%)',
  '--muted': 'hsl(240 4.8% 95.9%)',
  '--muted-foreground': 'hsl(240 3.8% 46.1%)',
  '--accent': 'hsl(240 4.8% 95.9%)',
  '--accent-foreground': 'hsl(240 5.9% 10%)',
  '--destructive': 'hsl(0 84.2% 60.2%)',
  '--destructive-foreground': 'hsl(0 0% 98%)',
  '--border': 'hsl(240 5.9% 90%)',
  '--input': 'hsl(240 5.9% 90%)',
  '--ring': 'hsl(240 5.9% 10%)',
  // 主要区域
  '--g-main-area-bg': 'hsl(0 0% 95%)',
  // 头部
  '--g-header-bg': 'var(--background)',
  '--g-header-color': 'var(--foreground)',
  '--g-header-menu-color': 'var(--accent-foreground)',
  '--g-header-menu-hover-bg': 'var(--accent)',
  '--g-header-menu-hover-color': 'var(--accent-foreground)',
  '--g-header-menu-active-bg': 'var(--primary)',
  '--g-header-menu-active-color': 'var(--primary-foreground)',
  // 主导航
  '--g-main-sidebar-bg': 'var(--background)',
  '--g-main-sidebar-menu-color': 'var(--accent-foreground)',
  '--g-main-sidebar-menu-hover-bg': 'var(--accent)',
  '--g-main-sidebar-menu-hover-color': 'var(--accent-foreground)',
  '--g-main-sidebar-menu-active-bg': 'var(--primary)',
  '--g-main-sidebar-menu-active-color': 'var(--primary-foreground)',
  // 次导航
  '--g-sub-sidebar-bg': 'var(--background)',
  '--g-sub-sidebar-menu-color': 'var(--accent-foreground)',
  '--g-sub-sidebar-menu-hover-bg': 'var(--accent)',
  '--g-sub-sidebar-menu-hover-color': 'var(--accent-foreground)',
  '--g-sub-sidebar-menu-active-bg': 'var(--primary)',
  '--g-sub-sidebar-menu-active-color': 'var(--primary-foreground)',
  // 标签栏
  '--g-tabbar-bg': 'var(--g-main-area-bg)',
  '--g-tabbar-dividers-bg': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-color': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-hover-bg': 'var(--border)',
  '--g-tabbar-tab-hover-color': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-active-bg': 'var(--background)',
  '--g-tabbar-tab-active-color': 'var(--foreground)',
  // 工具栏
  '--g-toolbar-bg': 'var(--background)',
}

export const darkTheme = {
  'color-scheme': 'dark',
  // shadcn
  '--background': 'hsl(240 10% 3.9%)',
  '--foreground': 'hsl(0 0% 98%)',
  '--card': 'hsl(240 10% 3.9%)',
  '--card-foreground': 'hsl(0 0% 98%)',
  '--popover': 'hsl(240 10% 3.9%)',
  '--popover-foreground': 'hsl(0 0% 98%)',
  '--primary': 'hsl(0 0% 98%)',
  '--primary-foreground': 'hsl(240 5.9% 10%)',
  '--secondary': 'hsl(240 3.7% 15.9%)',
  '--secondary-foreground': 'hsl(0 0% 98%)',
  '--muted': 'hsl(240 3.7% 15.9%)',
  '--muted-foreground': 'hsl(240 5% 64.9%)',
  '--accent': 'hsl(240 3.7% 15.9%)',
  '--accent-foreground': 'hsl(0 0% 98%)',
  '--destructive': 'hsl(0 62.8% 30.6%)',
  '--destructive-foreground': 'hsl(0 0% 98%)',
  '--border': 'hsl(240 3.7% 15.9%)',
  '--input': 'hsl(240 3.7% 15.9%)',
  '--ring': 'hsl(240 4.9% 83.9%)',
  // 主要区域
  '--g-main-area-bg': 'var(--background)',
  // 头部
  '--g-header-bg': 'var(--background)',
  '--g-header-color': 'var(--foreground)',
  '--g-header-menu-color': 'var(--muted-foreground)',
  '--g-header-menu-hover-bg': 'var(--muted)',
  '--g-header-menu-hover-color': 'var(--muted-foreground)',
  '--g-header-menu-active-bg': 'var(--accent)',
  '--g-header-menu-active-color': 'var(--accent-foreground)',
  // 主导航
  '--g-main-sidebar-bg': 'var(--background)',
  '--g-main-sidebar-menu-color': 'var(--muted-foreground)',
  '--g-main-sidebar-menu-hover-bg': 'var(--muted)',
  '--g-main-sidebar-menu-hover-color': 'var(--muted-foreground)',
  '--g-main-sidebar-menu-active-bg': 'var(--accent)',
  '--g-main-sidebar-menu-active-color': 'var(--accent-foreground)',
  // 次导航
  '--g-sub-sidebar-bg': 'var(--background)',
  '--g-sub-sidebar-menu-color': 'var(--muted-foreground)',
  '--g-sub-sidebar-menu-hover-bg': 'var(--muted)',
  '--g-sub-sidebar-menu-hover-color': 'var(--muted-foreground)',
  '--g-sub-sidebar-menu-active-bg': 'var(--accent)',
  '--g-sub-sidebar-menu-active-color': 'var(--accent-foreground)',
  // 标签栏
  '--g-tabbar-bg': 'var(--g-main-area-bg)',
  '--g-tabbar-dividers-bg': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-color': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-hover-bg': 'var(--accent) / 50%',
  '--g-tabbar-tab-hover-color': 'var(--accent-foreground) / 50%',
  '--g-tabbar-tab-active-bg': 'var(--secondary)',
  '--g-tabbar-tab-active-color': 'var(--foreground)',
  // 工具栏
  '--g-toolbar-bg': 'var(--background)',
}
