// <auto-generated />
using ElectronNet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129164432_ChangeBlobToInteger")]
    partial class ChangeBlobToInteger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ElectronNet.Models.GlobalStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<long?>("ActiveUserSteamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_user_steam_id")
                        .HasComment("当前登录用户的 Steam ID");

                    b.Property<int>("RefreshTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_time")
                        .HasComment("刷新时间");

                    b.Property<int?>("RunningAppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("running_app_id")
                        .HasComment("Steam 对外显示的当前运行的 App ID（同时只有一个）");

                    b.Property<string>("SteamClientDll64Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_client_dll_64_path")
                        .HasComment("steamclient64.dll 文件路径");

                    b.Property<string>("SteamClientDllPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_client_dll_path")
                        .HasComment("steamclient.dll 文件路径");

                    b.Property<string>("SteamExePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_exe_path")
                        .HasComment("Steam 可执行文件路径");

                    b.Property<string>("SteamPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_path")
                        .HasComment("Steam 安装路径");

                    b.Property<int?>("SteamPid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_pid")
                        .HasComment("Steam 进程 PID");

                    b.Property<int?>("SteamUserRefreshTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_user_refresh_time")
                        .HasComment("steamUser 表刷新时间");

                    b.HasKey("Id");

                    b.ToTable("global_status", null, t =>
                        {
                            t.HasComment("全局状态表（单行数据表）");

                            t.HasCheckConstraint("global_status_check_id", "id = 1");
                        });
                });

            modelBuilder.Entity("ElectronNet.Models.SteamApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id")
                        .HasComment("App ID");

                    b.Property<long?>("AppOnDisk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_on_disk")
                        .HasComment("应用文件占用大小");

                    b.Property<long?>("AppOnDiskReal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_on_disk_real")
                        .HasComment("应用文件真实占用大小");

                    b.Property<string>("Developer")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("developer")
                        .HasComment("开发者");

                    b.Property<string>("InstallDir")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("install_dir")
                        .HasComment("本地安装目录名称");

                    b.Property<string>("InstallDirPath")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("install_dir_path")
                        .HasComment("本地安装目录绝对路径");

                    b.Property<bool>("Installed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installed")
                        .HasComment("是否已本地安装");

                    b.Property<bool?>("IsFreeApp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_free_app")
                        .HasComment("是否是免费应用");

                    b.Property<bool>("IsRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_running")
                        .HasComment("是否正在运行");

                    b.Property<string>("Name")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("应用名称");

                    b.Property<string>("NameLocalizedJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("name_localized")
                        .HasComment("应用本地化名称 JSON 对象");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher")
                        .HasComment("发布者");

                    b.Property<int>("RefreshTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_time")
                        .HasComment("刷新时间");

                    b.Property<int?>("SteamReleaseDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_release_date")
                        .HasComment("发布日期");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasComment("应用类型");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex(new[] { "Installed" }, "steam_app_installed_idx");

                    b.HasIndex(new[] { "Name" }, "steam_app_name_idx");

                    b.ToTable("steam_app", null, t =>
                        {
                            t.HasComment("Steam 应用表");
                        });
                });

            modelBuilder.Entity("ElectronNet.Models.SteamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id")
                        .HasComment("Account ID");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_name")
                        .HasComment("账号名");

                    b.Property<bool?>("AllowAutoLogin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_auto_login")
                        .HasComment("是否允许自动登录");

                    b.Property<string>("AnimatedAvatar")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("animated_avatar")
                        .HasComment("动画头像 Base64");

                    b.Property<string>("AvatarFrame")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_frame")
                        .HasComment("头像边框 Base64");

                    b.Property<string>("AvatarFull")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_full")
                        .HasComment("全尺寸头像（184x184）Base64");

                    b.Property<string>("AvatarMedium")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_medium")
                        .HasComment("中等尺寸头像（64x64）Base64");

                    b.Property<string>("AvatarSmall")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_small")
                        .HasComment("小尺寸头像（32x32）Base64");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasComment("等级");

                    b.Property<string>("LevelClass")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("level_class")
                        .HasComment("等级样式类");

                    b.Property<bool?>("MostRecent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("most_recent")
                        .HasComment("是否最近登录");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("persona_name")
                        .HasComment("昵称");

                    b.Property<bool?>("RememberPassword")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remember_password")
                        .HasComment("是否记住密码");

                    b.Property<bool?>("SkipOfflineModeWarning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skip_offline_mode_warning")
                        .HasComment("是否跳过离线模式警告");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_id")
                        .HasComment("Steam ID");

                    b.Property<int?>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp")
                        .HasComment("最近登录时间");

                    b.Property<bool?>("WantsOfflineMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wants_offline_mode")
                        .HasComment("是否开启离线模式");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("steam_user", null, t =>
                        {
                            t.HasComment("Steam 用户表");
                        });
                });

            modelBuilder.Entity("ElectronNet.Models.UseAppRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("ID");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id")
                        .HasComment("使用的 App ID");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration")
                        .HasComment("持续使用时间");

                    b.Property<int?>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_time")
                        .HasComment("结束使用的 Unix 时间戳");

                    b.Property<int>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_time")
                        .HasComment("开始使用的 Unix 时间戳");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steam_id")
                        .HasComment("使用 App 的 Steam ID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppId" }, "use_app_record_app_id_idx");

                    b.HasIndex(new[] { "StartTime" }, "use_app_record_start_time_idx");

                    b.HasIndex(new[] { "SteamId", "AppId" }, "use_app_record_steam_id_app_id_idx");

                    b.HasIndex(new[] { "SteamId" }, "use_app_record_steam_id_idx");

                    b.ToTable("use_app_record", null, t =>
                        {
                            t.HasComment("应用使用记录表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
